// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	// Primary Key
	Uuid      uuid.UUID      `json:"uuid"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
}

type ComparativeAnalysis struct {
	// Primary Key
	Uuid uuid.UUID `json:"uuid"`
	// Foreign Key
	TenantUuid                       uuid.NullUUID  `json:"tenant_uuid"`
	Date                             sql.NullTime   `json:"date"`
	ProjectedVsActualRevenue         sql.NullString `json:"projected_vs_actual_revenue"`
	BudgetVsActualRevenueSharing     sql.NullString `json:"budget_vs_actual_revenue_sharing"`
	BottomRateVsActualRevenueSharing sql.NullString `json:"bottom_rate_vs_actual_revenue_sharing"`
	CreatedAt                        time.Time      `json:"created_at"`
}

type Location struct {
	// Primary Key
	Uuid      uuid.UUID      `json:"uuid"`
	Name      sql.NullString `json:"name"`
	Address   sql.NullString `json:"address"`
	CreatedAt time.Time      `json:"created_at"`
}

type PerformanceMetric struct {
	// Primary Key
	Uuid uuid.UUID `json:"uuid"`
	// Foreign Key
	TenantUuid                             uuid.NullUUID  `json:"tenant_uuid"`
	Date                                   sql.NullTime   `json:"date"`
	PerformancePercentageForRevenue        sql.NullString `json:"performance_percentage_for_revenue"`
	PerformancePercentageForRevenueSharing sql.NullString `json:"performance_percentage_for_revenue_sharing"`
	CreatedAt                              time.Time      `json:"created_at"`
}

type RevenueSharing struct {
	// Primary Key
	Uuid uuid.UUID `json:"uuid"`
	// Foreign Key
	TenantUuid               uuid.NullUUID  `json:"tenant_uuid"`
	PeriodStart              sql.NullTime   `json:"period_start"`
	PeriodEnd                sql.NullTime   `json:"period_end"`
	RevenueSharingPercentage sql.NullString `json:"revenue_sharing_percentage"`
	TotalRevenue             sql.NullString `json:"total_revenue"`
	TotalRevenueSharing      sql.NullString `json:"total_revenue_sharing"`
	Remarks                  sql.NullString `json:"remarks"`
	CreatedAt                time.Time      `json:"created_at"`
}

type SalesDatum struct {
	// Primary Key
	Uuid uuid.UUID `json:"uuid"`
	// Foreign Key
	TenantUuid           uuid.NullUUID  `json:"tenant_uuid"`
	Date                 sql.NullTime   `json:"date"`
	ProjectedRevenue     sql.NullString `json:"projected_revenue"`
	ActualRevenue        sql.NullString `json:"actual_revenue"`
	BudgetRevenue        sql.NullString `json:"budget_revenue"`
	RevenueSharingAmount sql.NullString `json:"revenue_sharing_amount"`
	CreatedAt            time.Time      `json:"created_at"`
}

type Tenant struct {
	// Primary Key
	Uuid uuid.UUID `json:"uuid"`
	// Foreign Key
	LocationUuid uuid.NullUUID `json:"location_uuid"`
	// Foreign Key, Nullable
	CategoryUuid             uuid.NullUUID  `json:"category_uuid"`
	Name                     sql.NullString `json:"name"`
	AreaSize                 sql.NullString `json:"area_size"`
	BottomRatePerMonth       sql.NullString `json:"bottom_rate_per_month"`
	RevenueSharingPercentage sql.NullString `json:"revenue_sharing_percentage"`
	CreatedAt                time.Time      `json:"created_at"`
}
