// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteTenant(ctx context.Context, argUuid uuid.UUID) error
	GetTenant(ctx context.Context, argUuid uuid.UUID) (Tenant, error)
	GetTenantForUpdate(ctx context.Context, argUuid uuid.UUID) (Tenant, error)
	ListTenant(ctx context.Context, arg ListTenantParams) ([]Tenant, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
